// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8EUbzuGS8PwfJi2R5grBMJ4t-t6xWPw4',
    appId: '1:193230616388:web:6a0047bf3de2b354118911',
    messagingSenderId: '193230616388',
    projectId: 'weatherapp-182f0',
    authDomain: 'weatherapp-182f0.firebaseapp.com',
    storageBucket: 'weatherapp-182f0.appspot.com',
    measurementId: 'G-H0SLDNGV2S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDVSBnw95_pF48E3dFHihr0AE183lDnVU',
    appId: '1:193230616388:android:6c9de87f4452d400118911',
    messagingSenderId: '193230616388',
    projectId: 'weatherapp-182f0',
    storageBucket: 'weatherapp-182f0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBY30ra5rqkZoMJQVFY06vKeyYo5ek_ifg',
    appId: '1:193230616388:ios:88f17a45f998113b118911',
    messagingSenderId: '193230616388',
    projectId: 'weatherapp-182f0',
    storageBucket: 'weatherapp-182f0.appspot.com',
    iosClientId: '193230616388-mkfi7bk8ueokbp6tr8nc7av0isgoi68p.apps.googleusercontent.com',
    iosBundleId: 'com.example.weatherforecast',
  );
}
